name: Docker

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ros_distro: [foxy, humble]
        ros_version: [2]

    env:
      LATEST_DISTRO: humble

    permissions:
      contents: read
      # packages: write

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU 🎯
        uses: docker/setup-qemu-action@v2

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup buildx 🔧
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into Docker Hub 📨
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels)
      # https://github.com/docker/metadata-action
      - name: Extract metadata 🔍
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}
          flavor: |
            prefix=ros${{ matrix.ros_version }}-${{ matrix.ros_distro }}
            latest=${{ matrix.ros_distro == env.LATEST_DISTRO && github.event_name != 'pull_request' }}
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=sha,pattern={{sha}}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ github.sha }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image 🐳
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            ROS_VERSION=${{ matrix.ros_version }}
            ROS_DISTRO=${{ matrix.ros_distro }}
            INSTALL_ZSH="false"
            UPGRADE_PACKAGES="true"
            USERNAME=ubuntu
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
